# How to read single value from XLS(X) using pandas

https://techoverflow.net/2021/08/01/how-to-read-single-value-from-xlsx-using-pandas/#google_vignette

In [ ]:
import pandas as pd
from pathlib import Path
import xlwings as xw

In [ ]:
filename = r'P:\Working Folders\Hilton\Prescient.xlsm'
wbD      = pd.read_excel(pth, sheet_name = 'Links')

In [ ]:
def read_value_from_excel(filename, sheetname = "Links", column = "D", row = 0):
    """Read a single cell value from an Excel file"""
    return pd.read_excel(filename, skiprows=row - 1, \
                         usecols=column, nrows=1, header=None, names=["Value"]).iloc[0]["Value"]

In [31]:
k = read_value_from_excel(filename, column="D", row = 1)
k

ParserError: Defining usecols without of bounds indices is not allowed. [3] are out of bounds. (sheet: 0)

In [10]:
pd.read_excel(filename, skiprows=row - 1, usecols=column, nrows=1, header=None, names=["Value"]).iloc[0]["Value"]

,pffb3,PFFB3 isn't loaded in the StatPro update file | PFFIF,"=HYPERLINK(""\\fileserver\pim-documents\AAPIM DEAL DOWNLOAD\ADMIN SETTLEMENT FILES\BESA MTM Files\"",UPPER($A1)&"" is""&IF(ISNA(VLOOKUP($A1,'\\fileserver\pim-documents\AAPIM DEAL DOWNLOAD\ADMIN SETTLEMENT FILES\BESA MTM Files\2022\Feb\[MTMDetailed20220218.xls]MTM'!$B$1:$B$65536,1,0)),"" NOT BESA Listed | ISIN: N/A | Mty: N/A "","" BESA-listed | ISIN: ""&XLOOKUP($A1,'\\fileserver\pim-documents\AAPIM DEAL DOWNLOAD\ADMIN SETTLEMENT FILES\BESA MTM Files\2022\Feb\[MTMDetailed20220218.xls]MTM'!$B$1:$B$65536,'\\fileserver\pim-documents\AAPIM DEAL DOWNLOAD\ADMIN SETTLEMENT FILES\BESA MTM Files\2022\Feb\[MTMDetailed20220218.xls]MTM'!$C$1:$C$65536)&"" | Maturity: ""&TEXT(VLOOKUP($A1,'\\fileserver\pim-documents\AAPIM DEAL DOWNLOAD\ADMIN SETTLEMENT FILES\BESA MTM Files\2022\Feb\[MTMDetailed20220218.xls]MTM'!$B$1:$D$65536,3,0),""ddd d mmm yyyy""))&"" | Circ6: ""&IF(ISNUMBER(MATCH($A$1,'\\fileserver.prescient.local\pim-business\Business Practice\Medical Schemes\[20220117 MSA Circ6 Categorisations.xlsx]JSEDebt&Equity31Dec2021'!$A:$A,0)),XLOOKUP($A$1,'\\fileserver.prescient.local\pim-business\Business Practice\Medical Schemes\[20220117 MSA Circ6 Categorisations.xlsx]JSEDebt&Equity31Dec2021'!$A:$A,'\\fileserver.prescient.local\pim-business\Business Practice\Medical Schemes\[20220117 MSA Circ6 Categorisations.xlsx]JSEDebt&Equity31Dec2021'!$K:$K),""No"")&"" | ""&HYPERLINK(""\\fileserver.prescient.local\Working-Folders\Hilton\Bloomberg\BX 30jun2021.xlsx"","" MCap = ZAR""&IF(ISNA(VLOOKUP($A1,'\\fileserver.prescient.local\Working-Folders\Hilton\Bloomberg\[BX 30Jun2021.xlsx]BBG'!$A:$A,1,0)),"" 0-0 "",FIXED(VLOOKUP($A1,'\\fileserver.prescient.local\Working-Folders\Hilton\Bloomberg\[BX 30Jun2021.xlsx]BBG'!$A:$E,5,0)/1000000000,3))&""bn at 30Jun2021""))",Raé reporting,StatPro PROD,StatPro errors,Crisps,"PIM credit ratings, CRXX",ISIN lookup,"Overdrafts folder, OD, ODx",...,Forward,Future,Option,Swap,Unnamed: 17,Unnamed: 18,Unnamed: 19,"BD14: , Hilton , Nazley",Unnamed: 21,Unnamed: 22
0,ppos,Prescient Positive Return QuantPlus Fund (PPOS),NaN,python reports,StatPro PROD EXPORT,StatPro run errors folder,Data maintenance,Moody's,S&P,Fitch,...,commodity,commodity,commodity,cash flows,NaN,NaN,NaN,NaN,NaN,NaN
1,PPOS Rules,PPOS is a PIM fund and a PMC UT,NaN,structures.xlsm,StatPro Reports Export,"StatPro rerun, re-run process",EXTAMDATA P:,A1,A+,A+,...,OTC,exchange,exchange / OTC,OTC,NaN,NaN,NaN,NaN,NaN,"nth occurrence of characters, Excel"
2,PPOS mod duration: 0 yrs,PPOS benchmark index is,NaN,py reports local,StatPro Instruments,StatPro BAARs,2AXX,Aa2,AA,AA,...,negotiable,standardised,standardised,negotiable,NaN,NaN,NaN,NaN,NaN,NaN
3,Custodian: STANDARD BANK,MultAsst | ASISA:,NaN,test folder,StatPro P: RUN folder,StatPro UAT EXTAMDATA,Dates,Aa2,AA,AA,...,at maturity,up to maturity,up to maturity,at maturity,NaN,NaN,NaN,NaN,NaN,server change: \\pim-cpt-fs\profile$ to \\pre-...
4,2023-12-13 00:00:00,"Duration: -5 days, ~ -0.013699 yr, 3 network ...",Breach register & aged analysis,C:\..\py,Portal Daily Rules Checklist,StatPro batch error logs,DSQA data maint,A2,A,A,...,obligation,obligation,right,obligation,NaN,NaN,NaN,gearing,borrowing to fund operations; incurring borrow...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,NaN,Staff,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
503,NaN,Staff CVs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506,NaN,Living Hands Trust v Old Mutual case 42728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
k = wbD[0:0]
k

Empty DataFrame
Columns: [pffb3, PFFB3 isn't loaded in the StatPro update file  |  PFFIF, =HYPERLINK("\\fileserver\pim-documents\AAPIM DEAL DOWNLOAD\ADMIN SETTLEMENT FILES\BESA MTM Files\",UPPER($A1)&" is"&IF(ISNA(VLOOKUP($A1,'\\fileserver\pim-documents\AAPIM DEAL DOWNLOAD\ADMIN SETTLEMENT FILES\BESA MTM Files\2022\Feb\[MTMDetailed20220218.xls]MTM'!$B$1:$B$65536,1,0))," NOT BESA Listed | ISIN: N/A | Mty: N/A  "," BESA-listed | ISIN: "&XLOOKUP($A1,'\\fileserver\pim-documents\AAPIM DEAL DOWNLOAD\ADMIN SETTLEMENT FILES\BESA MTM Files\2022\Feb\[MTMDetailed20220218.xls]MTM'!$B$1:$B$65536,'\\fileserver\pim-documents\AAPIM DEAL DOWNLOAD\ADMIN SETTLEMENT FILES\BESA MTM Files\2022\Feb\[MTMDetailed20220218.xls]MTM'!$C$1:$C$65536)&" | Maturity: "&TEXT(VLOOKUP($A1,'\\fileserver\pim-documents\AAPIM DEAL DOWNLOAD\ADMIN SETTLEMENT FILES\BESA MTM Files\2022\Feb\[MTMDetailed20220218.xls]MTM'!$B$1:$D$65536,3,0),"ddd d mmm yyyy"))&" |  Circ6: "&IF(ISNUMBER(MATCH($A$1,'\\fileserver.prescient.local\pim-business\Business Practice\Medical Schemes\[20220117 MSA Circ6 Categorisations.xlsx]JSEDebt&Equity31Dec2021'!$A:$A,0)),XLOOKUP($A$1,'\\fileserver.prescient.local\pim-business\Business Practice\Medical Schemes\[20220117 MSA Circ6 Categorisations.xlsx]JSEDebt&Equity31Dec2021'!$A:$A,'\\fileserver.prescient.local\pim-business\Business Practice\Medical Schemes\[20220117 MSA Circ6 Categorisations.xlsx]JSEDebt&Equity31Dec2021'!$K:$K),"No")&" | "&HYPERLINK("\\fileserver.prescient.local\Working-Folders\Hilton\Bloomberg\BX 30jun2021.xlsx"," MCap = ZAR"&IF(ISNA(VLOOKUP($A1,'\\fileserver.prescient.local\Working-Folders\Hilton\Bloomberg\[BX 30Jun2021.xlsx]BBG'!$A:$A,1,0))," 0-0 ",FIXED(VLOOKUP($A1,'\\fileserver.prescient.local\Working-Folders\Hilton\Bloomberg\[BX 30Jun2021.xlsx]BBG'!$A:$E,5,0)/1000000000,3))&"bn at 30Jun2021")), Raé reporting, StatPro PROD, StatPro errors, Crisps, PIM credit ratings, CRXX, ISIN lookup, Overdrafts folder, OD, ODx, Excel Add-ins folder, Unnamed: 11, Trait, Forward, Future, Option, Swap, Unnamed: 17, Unnamed: 18, Unnamed: 19, BD14: , Hilton , Nazley, Unnamed: 21, Unnamed: 22]
Index: []

[0 rows x 23 columns]

In [132]:
# select a fund and filter the holdings sheet by that fund name
fnd = 'GA Empolyees Medical BF'

t1 = wbH[wbH['Entity Name'] == fnd]
t2 = wbD[wbD['Entity Name'] == fnd]


t1.reset_index(level = 1)

IndexError: Too many levels: Index has only 1 level, not 2

In [118]:
# copy dataframes to existing 'Data' and 'Deltas' sheets
fnd = 'GA Empolyees Medical BF'

shtData.range('A1').value = wbH[wbH['Entity Name'] == fnd].reset_index(drop = True)
shtDeltas.range('A1').value = wbD[wbD['Entity Name'] == fnd].reset_index(drop = True)

# ... and then save the workbook