In [3]:
import pandas as pd

In [20]:
data = pd.read_excel(r'C:\Users\hilton.netta\Downloads\poster.xlsx', sheet_name = 'tab', usecols = 'A:I').dropna(subset = 'Investment Type')
df = pd.DataFrame(data, columns=['Investment Type', 'i Issue Name', 'Primary Asset ID', 'Closing Exposure PA'])
df = df.rename(columns={'Investment Type': 'Type', 'Primary Asset ID': 'Asset ID', 'i Issue Name': 'Description', 'Closing Exposure PA': 'Exposure (ZAR)'})
df_top10 = df.loc[(~df['Type'].isin(['CASH', 'SYTH'])) & (~df['Description'].str.contains('REPO'))\
].nlargest(10, 'Exposure (ZAR)').reset_index(drop = True)
df_top10

,Type,Description,Asset ID,Exposure (ZAR)
0,FI,RSA R2035 8.875% 280235,R2035,1.307781e+08
1,FT,MSCI EmgMkt Dec25,MESZ5,1.221696e+08
2,FT,MSCI World Index Dec25,ZWPZ5,1.151138e+08
3,OP,18DEC25 ALSI 105500P,18DEC25 ALSI 105500P,8.560925e+07
4,EQ,iShares USD Floating Rate Bond,BDFGJ62,8.275677e+07
5,FI,RSA R2037 8.5% 310137,R2037,7.843352e+07
6,FT,19MAR26 ALSI,19MAR26 ALSI,6.986626e+07
7,EQ,iShares USD Short Duration Hig,BZ17CN1,5.585200e+07
8,FI,RSA 2026 Dollar Bond (SOAF 4 7/8 04/26) Unsecured,US836205AT15,5.121600e+07
9,FT,US 2YR NOTE (CBT) Dec25,TUZ5,3.925052e+07

In [19]:
df_top10 = df.loc[(~df['Type'].isin(['CASH', 'SYTH'])) & (~df['Description'].str.contains('REPO'))\
].nlargest(10, 'Exposure (ZAR)').reset_index(drop = True)
df_top10

,Type,Description,Asset ID,Exposure (ZAR)
0,FI,RSA R2035 8.875% 280235,R2035,1.307781e+08
1,FT,MSCI EmgMkt Dec25,MESZ5,1.221696e+08
2,FT,MSCI World Index Dec25,ZWPZ5,1.151138e+08
3,OP,18DEC25 ALSI 105500P,18DEC25 ALSI 105500P,8.560925e+07
4,EQ,iShares USD Floating Rate Bond,BDFGJ62,8.275677e+07
5,FI,RSA R2037 8.5% 310137,R2037,7.843352e+07
6,FT,19MAR26 ALSI,19MAR26 ALSI,6.986626e+07
7,EQ,iShares USD Short Duration Hig,BZ17CN1,5.585200e+07
8,FI,RSA 2026 Dollar Bond (SOAF 4 7/8 04/26) Unsecured,US836205AT15,5.121600e+07
9,FT,US 2YR NOTE (CBT) Dec25,TUZ5,3.925052e+07

In [18]:
df[~df['Description'].str.contains('REPO')]

     Type                             Description  Asset ID  Exposure (ZAR)
0    CASH                               Audit Fee  AUDITFEE       -68119.22
1    CASH                       Australian Dollar   CASHAUD            0.00
2    CASH                  British Pound Sterling   CASHGBP        16795.65
3    CASH        Chinese Yuan Renminbi (offshore)   CASHCNH            0.00
4    CASH                            Danish Krone   CASHDKK            0.00
..    ...                                     ...       ...             ...
880  SYTH  Synthetic Cash_US 2YR NOTE (CBT) Dec25      TUZ5    -39256851.46
881  SYTH  Synthetic Cash_US 2YR NOTE (CBT) Sep25      TUU5            0.00
882  SYTH  Synthetic Cash_US 5YR NOTE (CBT) Dec25      FVZ5    -17473872.18
883  SYTH  Synthetic Cash_US ULTRA BOND CBT Dec25      WNZ5    -17234327.31
884  SYTH  Synthetic Cash_US ULTRA BOND CBT Sep25      WNU5            0.00

[817 rows x 4 columns]